### ISSUE TITLE
Modifying Verified Receipt

### ISSUE THREAD

**Issue by The-Young-Programer** [Zteller-Dev/Verified-Receipt#1]
@FridayCandour 

Oh OK so there are a couple of modifications that we also need to make on the receipt. 

1. In terms of the new implementations like the Direct Entry and Part-time...
2. The QR Code implementation
3. The Association Logo (This will be made available soon)
so these little adjustments needs to be made.

**Comment by FridayCandour** [comment]
on it

**Comment by FridayCandour** [comment]
please provide me api for backend

**Comment by FridayCandour** [comment]
to retrieve Duepayments and track payments if available

**Comment by The-Young-Programer** [comment]
@FridayCandour 


> to retrieve Duepayments and track payments if available

Check the Paystack, it's use in handling the payment
